"""Regenerate the independent coefficient fixture using a compiled DACE C core.

Usage: python generate_c_core.py /path/to/libdacecore.so
Requires the DYNAMIC memory model. This is a reference-data generator, not a
test/runtime dependency. Inputs and monomial ordering match api_completion.jl.
"""
import ctypes as c
import itertools
from pathlib import Path
import sys

lib = c.CDLL(sys.argv[1])

class DA(c.Structure):
    _fields_ = [("length", c.c_uint), ("capacity", c.c_uint), ("memory", c.c_void_p)]

P = c.POINTER(DA)

def function(name, arguments, result=None):
    f = getattr(lib, name)
    f.argtypes, f.restype = arguments, result
    return f

initialize = function("daceInitialize", [c.c_uint, c.c_uint])
allocate = function("daceAllocateDA", [P, c.c_uint])
release = function("daceFreeDA", [P])
setcoef = function("daceSetCoefficient", [P, c.POINTER(c.c_uint), c.c_double])
getcoef = function("daceGetCoefficient", [P, c.POINTER(c.c_uint)], c.c_double)
geterror = function("daceGetError", [], c.c_uint)
initialize(6, 3)
a, b = DA(), DA()
allocate(c.byref(a), 84)
allocate(c.byref(b), 84)
try:
    terms = [([0, 0, 0], 2.0), ([1, 0, 0], .1), ([0, 1, 0], .2),
             ([1, 0, 1], .05), ([0, 2, 0], .03)]
    for powers, value in terms:
        setcoef(c.byref(a), (c.c_uint * 3)(*powers), value)
    indices = sorted((p for p in itertools.product(range(7), repeat=3) if sum(p) <= 6),
                     key=lambda p: (sum(p), tuple(-i for i in p)))
    output = ["# Generated by test/reference/generate_c_core.py using UoA-AstroGroup/dace."]
    for name in ("SquareRoot", "MultiplicativeInverse", "Exponential", "Logarithm",
                 "Sine", "Cosine", "Tangent", "ArcTangent", "HyperbolicTangent",
                 "GammaFunction", "LogGammaFunction", "ErrorFunction"):
        function("dace" + name, [P, P])(c.byref(a), c.byref(b))
        assert geterror() == 0, name
        values = [getcoef(c.byref(b), (c.c_uint * 3)(*p)) for p in indices]
        output.extend([f"[{name}]", "coefficients = " + repr(values)])
    target = Path(__file__).resolve().parents[1] / "data/c_core_coefficients.toml"
    target.write_text("\n".join(output) + "\n")
finally:
    release(c.byref(a))
    release(c.byref(b))
