name: Run tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.10', '1']

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_NUM_THREADS: '4'
      - name: Build documentation and run examples
        if: matrix.julia-version == '1.10'
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg
          Pkg.develop(path=".")
          Pkg.instantiate()
          include("docs/make.jl")
